### ISSUE TITLE
`<ShowMore />` breaks when used with content with dynamic width

### ISSUE THREAD

**Issue by artashes-sanoyan** [remanufacturing/react-truncate#19]
### First of all thanks for this amazing library and great documentation.

I'm using `<ShowMore />` component which works perfectly fine unless you're dealing with an element that should have dynamic width depending on the content that it's rendering. Essentially the width of the parent component should be "auto" or "fit-content". I was able to achieve this with [react-show-more-text](https://github.com/devzonetech/react-show-more-text) but because of some other issues had to look for some other lbirary. 

This is a Vite and React [project](https://stackblitz.com/edit/vitejs-vite-dab866?file=src%2FApp.tsx,src%2FApp.css,src%2Fmain.tsx&terminal=dev) showcasing the issue.

### Why do I need this 

Essentially I need to display list of message bubbles containing text that should be truncated if the lines required to display it are more than 20. The content's length can basically vary from single word or letter to 100 of lines. And the surrounding bubble of that message must adapt to the size of text it's rendering (basically logic behind any messenger's bubble component).

**Is this even something that's possible ? I'm looking at this from a wrong perspective maybe ?**

Another minor note, I noticed that you're not taking into account the `letter-spacing` of the element when calculating the width which from my understanding will affect the component's behavior. Tell me if I'm wrong.

**Comment by chengpeiquan** [comment]
Thank you for your attention. I'm quite busy recently, but I will follow up on this issue.

**Comment by artashes-sanoyan** [comment]
Thanks for the response.

 I've found a workaround to this issue.
 At the moment before rendering the component I'm doing one extra calculation to decide if the text can be rendered as a single line text within given `max-width`. if that's the case, than that means that I don't need to truncate the text anyways. If the opposite is the case, meaning the text cannot be rendered within single line that means that I already know what is going to be the width of the component, it's going to be the `max-width`.
 
 to make those measurements I'm using the same technic, creating a canvas for each potential truncatable component, copying the styles from the element (`font-weight`, `font-style`, `font-size`, `font-family` and also `letter-spacing` which affects the calculations as well) and measuring the text. If measured width exceeds the `max-width` I'm using `<ShowMore />` otherwise simple `span` will do the job.
 
### The `letter-spacing`

I've found that excluding `letter-spacing` breaks the logic for elements that have non-default `letter-spacing`. I've copied the `<Truncate />` and `<ShowMore />`  components from this library into my own codebase and included `letter-spacing` as well. Everything seems to work fin. If author is interested I can create a PR with this property included, it's basically a one-liner.

Thanks again.

**Comment by chengpeiquan** [comment]
Thx! I looking forward to it, welcome PR!
